title: Footprints Preschool
url: 'https://www.footprintspreschool.nz'
baseurl:

url_dev: 'https://haloed-bear.cloudvent.net'
imgix_url: 'https://footprints-preschool.imgix.net'

kramdown:
  auto_ids: false
  

# Note: Need to change the API_KEY - THIS IS FOR ALTON DRILLING
google_maps_javascript_api_key: AIzaSyDHJOM0HUXycikhMCYbgLMLGyUCiBqt1TI
google_maps_latitude: -37.391655
google_maps_longitude: 175.838012
google_maps_zoom: 14

social:
  default_image: /images/fb-hero.jpg

_comments:

collections:
  staff:
    output: false

_options:
  slider_image:
    width: 1600
    resize_style: contain
    expandable: true
    uploads_dir: "uploads/slider"
  hero_image:
    width: 1600
    height: 400
    resize_style: contain
    expandable: true
    uploads_dir: "uploads/hero/"
  gallery_image:
    width: 1600
    height: 1400
    resize_style: contain
    expandable: true
    uploads_dir: "uploads/gallery/"
  content:
    width: 800
    height: 1200
    resize_style: contain
    uploads_dir: "uploads/content/"
  _block:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    link: true
    image: true
    numberedlist: true
    bulletedlist: true
    table: true
    right: align-to-right

paginate: 24
paginate_path: '/blog/:num/'
permalink: '/blog/:year/:month/:day/:title/'

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
      